name: Update Config YAML

on:
  workflow_run:
    workflows: ["Fetch PubMed Data"]
    types:
      - completed
  workflow_dispatch:   # optional manual trigger
jobs:
  update-config:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas pyyaml

      - name: Run update script
        run: python create_yaml.py

      - name: Commit and push config.yaml
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add config.yaml
          git diff --quiet || git commit -m "Update config.yaml via GitHub Actions"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
